/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import NapakalakiGame.CombatResult;
import NapakalakiGame.Napakalaki;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Rusillo
 */
public class NapakalakiView extends javax.swing.JFrame {

    
    private Napakalaki napakalakiModel;
    
    public void setNapakalaki(Napakalaki model){
        napakalakiModel = model;
        playerView1.setNapakalaki(napakalakiModel);
        monsterView1.setMonster(napakalakiModel.getCurrentMonster());
        monsterView1.setVisible(false);
        NextTurn.setVisible(false);
        Combat.setEnabled(false);
        RobarVisible.setEnabled(true);
        
        playerView1.setPlayer(napakalakiModel.getCurrentPlayer());
        setIconImage(new ImageIcon(getClass().getResource("../imagen/iconA.jpg")).getImage());
        setTitle("Napakalaki Antonio Maldonado");
       // resultado.setText("");
      
        //this.playerView1.setNapakalaki(model, this);

        //Finalizar con la siguiente orden para que los cambios se hagan efectivos
        repaint();

    }
    public NapakalakiView() {
        initComponents();
        setLocationRelativeTo(null); //supuestamente el centro
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resultado = new javax.swing.JLabel();
        monsterView1 = new GUI.MonsterView();
        SeeMonster = new javax.swing.JButton();
        Combat = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        NextTurn = new javax.swing.JButton();
        result = new javax.swing.JLabel();
        playerView1 = new GUI.PlayerView();
        RobarVisible = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(250, 251, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusable(false);
        setFocusableWindowState(false);

        resultado.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        resultado.setForeground(new java.awt.Color(250, 0, 0));

        SeeMonster.setText("Ver Monstruo");
        SeeMonster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeeMonsterActionPerformed(evt);
            }
        });

        Combat.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 1, 12)); // NOI18N
        Combat.setForeground(new java.awt.Color(200, 0, 0));
        Combat.setText("¡¡COMBATE!!");
        Combat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CombatActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("RESULTADO:");

        NextTurn.setText("Siguiente turno");
        NextTurn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextTurnActionPerformed(evt);
            }
        });

        result.setFont(new java.awt.Font("MV Boli", 1, 36)); // NOI18N
        result.setForeground(new java.awt.Color(200, 0, 0));
        result.setToolTipText("");

        RobarVisible.setText("Robar Visible");
        RobarVisible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RobarVisibleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(resultado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(playerView1, javax.swing.GroupLayout.PREFERRED_SIZE, 1294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(result, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SeeMonster, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(Combat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(NextTurn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(RobarVisible, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(monsterView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Combat, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NextTurn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SeeMonster, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RobarVisible, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)))
                        .addGap(93, 93, 93)
                        .addComponent(jLabel1)
                        .addGap(31, 31, 31)
                        .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(monsterView1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(playerView1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SeeMonsterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeeMonsterActionPerformed
        monsterView1.setVisible(true);
        playerView1.hacervisible(false);
        Combat.setEnabled(true);

        repaint();
    }//GEN-LAST:event_SeeMonsterActionPerformed

    private void CombatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CombatActionPerformed
                CombatResult res = napakalakiModel.developCombat();
        
        if (res == CombatResult.WIN){
            result.setText("Has Ganado");
        }
        else if(res == CombatResult.LOSE){
            result.setText("Has Perdido");
            playerView1.setBC(napakalakiModel.getCurrentMonster().getBadConsequence());
        }
        else if(res == CombatResult.LOSEANDCONVERT){
            result.setText("Has Perdido y te combiertes");
            playerView1.setBC(napakalakiModel.getCurrentMonster().getBadConsequence());
        }
        else if(res == CombatResult.WINGAME){
            result.setText("HAS GANADO EL JUEGO");
            monsterView1.setEnabled(false);
            NextTurn.setEnabled(false);
            SeeMonster.setEnabled(false);
            Combat.setEnabled(false);
            playerView1.hacervisible(false);           
        }
        
        setNapakalaki(napakalakiModel);
        monsterView1.setVisible(true); // quiero q quede desplegada vista monstruo
        SeeMonster.setEnabled(false);
        NextTurn.setVisible(true);
        playerView1.hacervisible(true);
        Combat.setEnabled(false);
        repaint();
    }//GEN-LAST:event_CombatActionPerformed

    private void NextTurnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextTurnActionPerformed
        if(napakalakiModel.nextTurnAllowed()){
            result.setText("");
            napakalakiModel.nextTurn();
            setNapakalaki(napakalakiModel);
            playerView1.hacervisible(true);
            SeeMonster.setEnabled(true);
        }
        else
            result.setText("DESCARTA ALGO");
         
    }//GEN-LAST:event_NextTurnActionPerformed

    private void RobarVisibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RobarVisibleActionPerformed
        //napakalakiModel
        napakalakiModel.stealToPreviousPlayer();
        result.setText("Se ha robado? :/");
        RobarVisible.setEnabled(false);
        playerView1.repaint();
    }//GEN-LAST:event_RobarVisibleActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Combat;
    private javax.swing.JButton NextTurn;
    private javax.swing.JButton RobarVisible;
    private javax.swing.JButton SeeMonster;
    private javax.swing.JLabel jLabel1;
    private GUI.MonsterView monsterView1;
    private GUI.PlayerView playerView1;
    private javax.swing.JLabel result;
    private javax.swing.JLabel resultado;
    // End of variables declaration//GEN-END:variables
}
