package GUI;

import NapakalakiGame.Prize;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rusillo
 */
public class PrizeView extends javax.swing.JPanel {

    private Prize prizeModel;
    /**
     * Creates new form Prize
     */
    
    public void setPrize(Prize p)
    {
        prizeModel = p;
        this.nLvl.setText(Integer.toString(p.getLvl()));
        this.nT.setText(Integer.toString(p.getTreasures()));
        
        repaint();
        revalidate();
    }
    public PrizeView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Niveles = new javax.swing.JLabel();
        nLvl = new javax.swing.JLabel();
        Tesoros = new javax.swing.JLabel();
        nT = new javax.swing.JLabel();

        Niveles.setText("Niveles:");

        nLvl.setText("nLvl");

        Tesoros.setText("Tesoros:");

        nT.setText("nT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Niveles)
                    .addComponent(Tesoros))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nT)
                    .addComponent(nLvl))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Niveles)
                    .addComponent(nLvl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tesoros)
                    .addComponent(nT))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Niveles;
    private javax.swing.JLabel Tesoros;
    private javax.swing.JLabel nLvl;
    private javax.swing.JLabel nT;
    // End of variables declaration//GEN-END:variables
}
